### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by kellrott** [bmeg/gaea#8]
Attempting to do import step, received

```
importing GeneExpression - ../sample/bcgsc.ca_STAD_IlluminaHiSeq_RNASeq.geneExp.tsv.GeneExpression.json
Traceback (most recent call last):
  File "./import-everything.py", line 17, in import_json
    conn.request('POST', '/message/' + data_type, open(path, 'rb'), headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 866, in send
    self.sock.sendall(datablock)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
```

**Comment by prismofeverything** [comment]
Ah, do a pull on the `importers` repo and try again, it was in a state where I was trying to import just GeneExpression instead of everything but GeneExpression.
